### ISSUE TITLE
Getting "Token exchange failed. Request status: 410" also after accepting terms online

### ISSUE THREAD

**Issue by mgartin** [skodaconnect/homeassistant-skodaconnect#242] opened 2023-12-11 21:14 UTC
I'm getting the following in the home assistant log:

Token exchange failed. Request status: 410

**Is this working in MySkoda app?***
I have logged out and in again in the MySkoda app on Android. I had already the latest version.

**Latest working release**
I use Home Assistant 2023.12.1, HACS 1.33.0. 

The integration reports: Firmware: 2017-11-24

**Debug logs**
```
2023-12-11 22:13:14.905 INFO (MainThread) [skodaconnect.connection] Unofficial Skoda Connect library, version 1.3.8
2023-12-11 22:13:14.905 INFO (MainThread) [skodaconnect.connection] Initiating new login
2023-12-11 22:13:15.895 ERROR (MainThread) [skodaconnect.connection] Token exchange failed. Request status: 410
2023-12-11 22:13:20.965 INFO (MainThread) [skodaconnect.connection] Unofficial Skoda Connect library, version 1.3.8
2023-12-11 22:13:20.966 INFO (MainThread) [skodaconnect.connection] Initiating new login
2023-12-11 22:13:21.951 ERROR (MainThread) [skodaconnect.connection] Token exchange failed. Request status: 410

```

**Installation:**
 - Home Assistant variant: HASS OS (latest stable)

**Comment by Farfar** [comment] 2023-12-11 21:23
Duplicate of #237, #238 and #241.
Please update to latest release which contains fix.

**Closed by Farfar** 2023-12-11 21:23 UTC
Labels: bug
