### ISSUE TITLE
Is VW/Skoda limiting API calls by third party (such as Home Assistant)?

### ISSUE THREAD

**Issue by erd82** [skodaconnect/homeassistant-skodaconnect#220] opened 2023-10-24 16:46 UTC
Since a few weeks I have problems getting any data in MySkoda Essentials app and in Home Assistant at all.
![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/63564291/c9ddb0d7-b24f-401d-9522-537fe49cb42a)

**The model of my Skoda is the Superb iV.**

In Home Assistant no Skoda Connect sensors are available: 
![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/63564291/4f6add40-3529-4106-a0bb-de73fb034c95)

The Skoda Connect integration is not able to initialize:
![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/63564291/0f74434e-b507-43aa-a8f8-41584ef92ae4)

In the history for the single sensors I suddenly noticed that data (and the complete integration) was available between 2am and around 10 am. After that the integration stopped working.
![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/63564291/38e000c8-7461-42d5-a4b8-bda070eec36c)

This problem seems to happen since the last visit to the garage where they have updated all software components of the car (incl. Infotainment system). 

Could it be that Skoda has implemented a more strict API call limitation now or they rather exclude third party software like this HA integration?

**Comment by dvx76** [comment] 2023-10-24 16:58
Yes, several other users have also raised similar observations, especially with the older API endpoints (all cars except Enyaq). Debug logs of the integration would confirm this, but likely it's the same issue.

You can try increasing the poll frequency (in the integration configuration) to 120s or 180s.

**Comment by erd82** [comment] 2023-10-24 17:07
@dvx76: Many thanks for the quick reply & confirmation! Ok, I will try with 120s polling frequency, first.

But how could VW/Skoda suddenly reduce / limit the service now? Beforehand it was working fine and without any issues. Three years ago I bought the car and was paid much money for it! And now they are limiting the functionality?

Oha, that's one more argument going away from VW/Skoda :-(. It seems as if German manufacturers are now cutting back more and more. sad!

**Comment by dvx76** [comment] 2023-10-24 17:17
I imagine they've been seeing a significant increase in API traffic over the past years, especially with the new EV models and third-party applications leveraging the APIs (HA is one, but apps like Pump or Tronity probably have a lot of users too). They should ramp up the API capacity instead, but who knows what's going on internally 🤷‍♂️

**Comment by asd20752** [comment] 2023-10-25 01:32
Having looked at the requests being sent every poll results for me in 6 polls and would expect it to change depending on the car. 
- Heater status
- General status
- Position
- Short term trip statistics
- Cyclic trip statistics
- Long term statistics

EV's should produce more requests with charging status. 

Could I ask what your polling frequency was before chaning to 120?

**Comment by sbeukers** [comment] 2023-10-25 09:33
> Having looked at the requests being sent every poll results for me in 6 polls and would expect it to change depending on the car.
> 
> * Heater status
> * General status
> * Position
> * Short term trip statistics
> * Cyclic trip statistics
> * Long term statistics
> 
> EV's should produce more requests with charging status.
> 
> Could I ask what your polling frequency was before chaning to 120s?

standard is 60s
from 2:00 till 11:00 is about 480 calls per day.
or every 3 min. with none to spare.

**Comment by Farfar** [comment] 2023-10-25 11:46
> > Having looked at the requests being sent every poll results for me in 6 polls and would expect it to change depending on the car.
> > 
> > * Heater status
> > * General status
> > * Position
> > * Short term trip statistics
> > * Cyclic trip statistics
> > * Long term statistics
> > 
> > EV's should produce more requests with charging status.
> > Could I ask what your polling frequency was before chaning to 120s?
> 
> standard is 60s from 2:00 till 11:00 is about 480 calls per day. or every 3 min. with none to spare.

Do you have anything else integrated with your Skoda? Smart charging or something else.

**Comment by asd20752** [comment] 2023-10-25 12:25
> > Having looked at the requests being sent every poll results for me in 6 polls and would expect it to change depending on the car.
> > 
> > * Heater status
> > * General status
> > * Position
> > * Short term trip statistics
> > * Cyclic trip statistics
> > * Long term statistics
> > 
> > EV's should produce more requests with charging status.
> > Could I ask what your polling frequency was before chaning to 120s?
> 
> standard is 60s from 2:00 till 11:00 is about 480 calls per day. or every 3 min. with none to spare.

What I am starting to consider is that this claim might be faulty. Since some people are not experiencing problems and others are. So what I am trying to figure out is what kind of limitations have been applied. 

My current hypothesis is that less API advanced cars stay within while the more API features the more requests and you hit the limit faster. 

For me with the example you gave at 60s from 02:00 to 11:00 the intuitive answer would be 540 requests in that time period. But I believe it is about 6 times as much 540x6=3240. 

If this is the case maybe giving the option to disable metrics not used to allow for faster poll frequency could be beneficial

**Comment by MReuter2203** [comment] 2023-10-25 13:56
Hi there,
same issue for me. Weeks ago, it worked like a charm.
So I wrote the support and the confirm me (after 8 email) that the 3third party tool is the issue and they restart the service every night for new.
That`s very sad and also strange. Some time ths service is not reachable after 4-5 hours they have restart their service. Sometime the service is reachable for 24 hours without any errors.
Is it possible to make an automation for different pollings for different times?
Because I don´t need the polling in the afternoon and at night.
Thank you
Marcus

**Comment by tjafbe** [comment] 2023-10-25 15:05
It could be a coincidence, but just like the OP I have a Superb iV, which also went into the garage where they updated all the software. I get exactly the same behavior as the OP. I'll try (severely) limiting the calls to see if that helps.

**Comment by riochicken** [comment] 2023-10-25 16:59
Since almost 3 weeks I am the proud owner of a Enyaq coupe and I was very happy with this hacs integration, since a week or so, the server side of skoda connect seems to be having issues, I even cannot start the my skoda app to check on my car or turn the pre heat on, so I think the servers at skoda can't handle the traffic or there is a DDoS attack every time over and over again, since it worked flawlessly at the beginning, my suspicion is that it's some form of attack, or there are a lot of extra myskoda users since I got my car... I hope they can solve it, for now it seems that they have closed the access to the API and so to this fine integration...

**Comment by sbeukers** [comment] 2023-10-25 19:01
> Since almost 3 weeks I am the proud owner of a Enyaq coupe and I was very happy with this hacs integration, since a week or so, the server side of skoda connect seems to be having issues, I even cannot start the my skoda app to check on my car or turn the pre heat on, so I think the servers at skoda can't handle the traffic or there is a DDoS attack every time over and over again, since it worked flawlessly at the beginning, my suspicion is that it's some form of attack, or there are a lot of extra myskoda users since I got my car... I hope they can solve it, for now it seems that they have closed the access to the API and so to this fine integration...

No it's not an attack. It's too much calls for a single car/account in one day. That is why it is again working every day at the same time again (02:00 CET for me)

**Comment by Farfar** [comment] 2023-10-25 19:16
What you might not realize is that all VAG cars (at least VW, Skoda, Seat and Cupra) use the same servers/API.
VAG changed their API in order to relieve the servers from some of the load instead of fixing their servers so they can handle the load.
The limit of number of polls/day does not help since the service is still as bad as always. The only effect is worse service for 3rd parties.
No matter what we do to fix the issues theese kind of problems will always return since this integration is in no way endorsed by Skoda/VAG.
It can stop working at any time and the only thing keeping it "online" is the time and dedication of developers for this and other 3rd party integrations for VAG connected cars.

Please keep information on topic, with facts and no speculation since it won't help anyone solve these issues.

**Comment by mydliar** [comment] 2023-10-25 21:15
I live in the UK, and my HA integration stopped working today. Neither I can login to MySkoda app, or in the browser. Looks like some kind of service outage.

**Comment by lapidu** [comment] 2023-10-26 05:14
Hello all,

I have tried to set the polling frequency to 1 hour. Unfortunately I get an error message. See attachment. 

Maybe it is a solution to set the polling frequency to 1-2 hours. And to trigger Force data refresh via automation. 

![Screenshot 2023-10-26 070030](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/28223007/e4e053a7-c63f-4d9d-9c3e-dc38d9933f5e)

![Screenshot 2023-10-26 070242](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/28223007/d0ec87ce-4f34-4e71-8766-feca3ca7a9de)

**Comment by ksvard** [comment] 2023-10-26 05:55
Owner of a Enyaq IV. Integration has been working fine until tonight. Today, when I try the api call directly in the browser,
**https://api.connect.skoda-auto.cz/api/v1/authentication/token/refresh?systemId=CONNECT,** 
 I get the following reply:
**503 Service Temporarily Unavailable**

**Comment by Farfar** [comment] 2023-10-26 05:57
> Owner of a Enyaq IV. Integration has been working fine until tonight. Today, when I try the api call directly in the browser, **https://api.connect.skoda-auto.cz/api/v1/authentication/token/refresh?systemId=CONNECT,** I get the following reply: **503 Service Temporarily Unavailable**

Not related to this issue.
The 503 is something wrong on server side.

**Comment by haraldpaulsen** [comment] 2023-10-26 08:37
This morning I couldn't log in to skoda, but suddenly it is working again. Nothing to do with the plugin, just Skoda/VW/VAG-things I guess.

**Comment by mydliar** [comment] 2023-10-26 09:46
> I live in the UK, and my HA integration stopped working today. Neither I can login to MySkoda app, or in the browser. Looks like some kind of service outage.

All started working again this morning. Also new MySkoda app appeared.

**Comment by basdp** [comment] 2023-10-26 21:48
Last week my Enyaq was mostly unavailable in the app and integration. Looks like I'm getting blocked by the API. Currently increased my polling rate to 120s, but that doesn't seem to fix it (tried for 3 days). Will update to 180s, but this is starting to become problematic.

**Comment by dvx76** [comment] 2023-10-27 09:26
I'm going to close this issue because this is a server-side issue on the VW/Skoda side. Everyone and everything is affected by this including the official Skoda App and web portal. There was also a pretty major API outage this week which certainly hasn't helped.

There are initiatives to alleviate the problem:
- Initiate polling ad-hoc (#212)
- @Farfar and others have been talking on Discord about allowing the polling interval to be dynamically updated (which would allow for example to bump the interval during the night)

PRs are welcome 😄

**Closed by dvx76** 2023-10-27 09:26 UTC

**Comment by basdp** [comment] 2023-10-27 10:40
Closing a ticket that reports a problme that makes this whole integration 100% unusable? Any work besides work on this would be in vain as I expect nobody would be using this integration anymore.
The workarounds mentioned are interesting but ultimately not sufficient (ad-hoc doesn't support the main use case of automation based on triggers like charger connected or charging started/stopped). 

I think the community needs to get in contact with VW/Skoda. I can be part of that but I'm currently only a user, not a representative of this project.

**Comment by dvx76** [comment] 2023-10-27 11:08
This is a problem which makes _any_ client, including the Skoda App itself, unusable. Keeping a ticket open for people to say "me too" won't help.

> I think the community needs to get in contact with VW/Skoda.

It's a risky play. There was some discussion around this in #215. The problem is that this is not a public API. The only reason this integration exists is because someone reverse-engineered the Skoda/VW/Seat Apps. The concern is that putting this on VWs radar might result in them closing it off further instead of helping. E.g. this is what happened to a similar project with Mazda:
- https://github.com/bdr99/node-mymazda
- https://github.com/github/dmca/blob/master/2023/10/2023-10-10-mazda.md

Trusted unofficial contacts creating a back-channel into VW/Skoda would be ideal.

> I can be part of that but I'm currently only a user, not a representative of this project.

Great. There is a Discord channel (linked in the README) where a lot of users and maintainers hang out. Feel free to contribute.

**Comment by erd82** [comment] 2023-11-06 08:52
Since last weekend the MySkoda Essential app seems to work again properly for my Superb iV?
BUT Home Assistant does react anymore at all. 
![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/63564291/7a6252e4-6926-449b-8cee-5a76af721736)
Did Skoda block HA completely now ?

**Comment by dvx76** [comment] 2023-11-06 08:55
@erd82 see #227 - please update to the latest version 1.2.7

**Comment by erd82** [comment] 2023-11-06 09:30
Couldn't answer quick enough :). yes 1.2.7 works again. Many thanks !!

**Comment by erd82** [comment] 2023-11-09 21:17
Again not working since yesterday 😒.

**Comment by dhoogfr** [comment] 2023-11-10 08:34
@erd82 which type of car do you have?
For me, the integration (with Enyaq) is still working

**Comment by erd82** [comment] 2023-11-10 08:46
@dhoogfr, I have a Superb iV.
Also the MySkoda App isn't working again (it's at least consistent) - see my original request.

**Comment by haraldpaulsen** [comment] 2023-11-10 10:35
To add a datapoint:Skoda citigo IVWhen I had polling set to 60 it would become unavailable after a while. At the moment I am using 120 and it appears to be stable.

**Comment by erd82** [comment] 2023-11-10 10:48
Mine is running with 180 s and it's breaking each day.
