### ISSUE TITLE
The integration does not work anymore

### ISSUE THREAD

**Issue by acuadulza** [skodaconnect/homeassistant-skodaconnect#243] opened 2023-12-12 09:46 UTC
Error message: "failed to set token for "connect": no valid tokens for client "connect"

**Is this working in MySkoda app?*** YES on Android apps and web
Logout and login in the MySkoda app, preferably on Android: DONE

**Installation:** 
 - Home Assistant variant: Hass OS 2023.12.1

**Comment by dvx76** [comment] 2023-12-12 09:51
Please check recent issues and new versions before raising an issue.

This is a duplicate of #237, #238, #241 and #242.

Fixes in https://github.com/skodaconnect/skodaconnect/pull/108 please update to the latest version of the integration.

**Closed by dvx76** 2023-12-12 09:51 UTC
Labels: bug
