### ISSUE TITLE
Enyaq sensors alternating between incorrect and correct status

### ISSUE THREAD

**Issue by lucius-the** [skodaconnect/homeassistant-skodaconnect#157] opened 2022-12-14 02:45 UTC
**Describe the bug**
Škoda Kodiaq Ambition. All windows show as opened and trunk shows as unlocked. They're closed and trunk locked, just checked it. Also in Android Škoda App windows show as closed and trunk locked.
I've tried force refresing, no change. I've tried removing and re-adding the integration, but no change,

**Installation:**
 - Home Assistant variant: Docker 2022.5.5
 - Python version: Python 3
 - Python library version: I don't know

**Comment by RamonQu** [comment] 2022-12-16 09:16
This looks like a duplicate of Issue https://github.com/lendy007/homeassistant-skodaconnect/issues/145 and https://github.com/lendy007/homeassistant-skodaconnect/issues/151

@lucius-the Can you look at the history of the applicable sensors within HA? Do they open/close several times during the day? If so, it has probably the same cause.

**Comment by Farfar** [comment] 2022-12-23 12:08
Sometimes the data on Skoda servers show incorrect values.
Can you provide debug logs? Otherwise I can't tell if it's actually an issue for this car or if it's an issue with stale data on servers.

**Comment by RamonQu** [comment] 2022-12-28 16:04
@lucius-the & @Farfar I gathered the debugging logs. It looks like the Skoda-servers are returning an overall 200 OK status message, but some in-line errors are included that are not handled. To make it even worse, the applicable entities are returned with UNKNOWN or None.

The wrong status codes are applicable on odometer, lights, doors and windows (including sunroof, lock-status, trunk, hood). The skoda server is returning a lot of errors during the whole day, so this was easy to capture.

For example the Home Assistant logbook returns the following on the status of window closed left back. It flips the status really a lot of time during the day.

![Pasted Graphic](https://user-images.githubusercontent.com/113984457/209839166-647e3e4c-c88e-41ad-82e1-ee30353945cb.jpg)


```
Window closed left back

Was closed
16:34:41 - 3 minutes ago

Was opened
16:32:35 - 5 minutes ago

Was closed
16:27:15 - 11 minutes ago

Was opened
16:26:13 - 12 minutes ago

Was closed
16:24:06 - 14 minutes ago
```


Hereby the contents of json with in-line errors. I included eight different calls so you take a look at how crappy the server answers are. Some calls are receiving more errors than others.

2022-12-28 16:25:06.241 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:25:08.024 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': '2022-12-28T13:18:32.05Z', 'status': {'open': 'NO', 'locked': 'YES'}, 'mileageInKm': 5150.0, 'doors': [{'name': 'BONNET', 'status': 'CLOSED'}, {'name': 'TRUNK', 'status': 'LOCKED'}, {'name': 'REAR_RIGHT', 'status': 'LOCKED'}, {'name': 'REAR_LEFT', 'status': 'LOCKED'}, {'name': 'FRONT_RIGHT', 'status': 'LOCKED'}, {'name': 'FRONT_LEFT', 'status': 'LOCKED'}], 'windows': [{'name': 'SUN_ROOF', 'status': 'CLOSED'}, {'name': 'ROOF_COVER', 'status': 'UNSUPPORTED'}, {'name': 'SUN_ROOF_REAR', 'status': 'UNSUPPORTED'}, {'name': 'FRONT_LEFT', 'status': 'CLOSED'}, {'name': 'FRONT_RIGHT', 'status': 'CLOSED'}, {'name': 'REAR_LEFT', 'status': 'CLOSED'}, {'name': 'REAR_RIGHT', 'status': 'CLOSED'}], 'lights': {'overallStatus': 'OFF', 'lightsStatus': [{'name': 'RIGHT', 'status': 'OFF'}, {'name': 'LEFT', 'status': 'OFF'}]}}, 'local': None, 'errors': []}

2022-12-28 16:26:08.232 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:26:13.337 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': '2022-12-28T13:18:13.739Z', 'status': {'open': 'UNKNOWN', 'locked': 'UNKNOWN'}, 'mileageInKm': None, 'doors': None, 'windows': None, 'lights': {'overallStatus': 'OFF', 'lightsStatus': [{'name': 'RIGHT', 'status': 'OFF'}, {'name': 'LEFT', 'status': 'OFF'}]}}, 'local': None, 'errors': [{'type': 'DOORS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/access/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'WINDOWS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/access/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'MILEAGE_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/measurements": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}]}

2022-12-28 16:27:13.228 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:27:15.589 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': '2022-12-28T13:18:32.05Z', 'status': {'open': 'NO', 'locked': 'YES'}, 'mileageInKm': 5150.0, 'doors': [{'name': 'BONNET', 'status': 'CLOSED'}, {'name': 'TRUNK', 'status': 'LOCKED'}, {'name': 'REAR_RIGHT', 'status': 'LOCKED'}, {'name': 'REAR_LEFT', 'status': 'LOCKED'}, {'name': 'FRONT_RIGHT', 'status': 'LOCKED'}, {'name': 'FRONT_LEFT', 'status': 'LOCKED'}], 'windows': [{'name': 'SUN_ROOF', 'status': 'CLOSED'}, {'name': 'ROOF_COVER', 'status': 'UNSUPPORTED'}, {'name': 'SUN_ROOF_REAR', 'status': 'UNSUPPORTED'}, {'name': 'FRONT_LEFT', 'status': 'CLOSED'}, {'name': 'FRONT_RIGHT', 'status': 'CLOSED'}, {'name': 'REAR_LEFT', 'status': 'CLOSED'}, {'name': 'REAR_RIGHT', 'status': 'CLOSED'}], 'lights': {'overallStatus': 'OFF', 'lightsStatus': [{'name': 'RIGHT', 'status': 'OFF'}, {'name': 'LEFT', 'status': 'OFF'}]}}, 'local': None, 'errors': []}

2022-12-28 16:28:15.230 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:28:18.111 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': '2022-12-28T13:18:32.05Z', 'status': {'open': 'NO', 'locked': 'YES'}, 'mileageInKm': 5150.0, 'doors': [{'name': 'BONNET', 'status': 'CLOSED'}, {'name': 'TRUNK', 'status': 'LOCKED'}, {'name': 'REAR_RIGHT', 'status': 'LOCKED'}, {'name': 'REAR_LEFT', 'status': 'LOCKED'}, {'name': 'FRONT_RIGHT', 'status': 'LOCKED'}, {'name': 'FRONT_LEFT', 'status': 'LOCKED'}], 'windows': [{'name': 'SUN_ROOF', 'status': 'CLOSED'}, {'name': 'ROOF_COVER', 'status': 'UNSUPPORTED'}, {'name': 'SUN_ROOF_REAR', 'status': 'UNSUPPORTED'}, {'name': 'FRONT_LEFT', 'status': 'CLOSED'}, {'name': 'FRONT_RIGHT', 'status': 'CLOSED'}, {'name': 'REAR_LEFT', 'status': 'CLOSED'}, {'name': 'REAR_RIGHT', 'status': 'CLOSED'}], 'lights': {'overallStatus': 'OFF', 'lightsStatus': [{'name': 'RIGHT', 'status': 'OFF'}, {'name': 'LEFT', 'status': 'OFF'}]}}, 'local': None, 'errors': []}


2022-12-28 16:29:18.233 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:29:23.320 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': None, 'status': {'open': 'UNKNOWN', 'locked': 'UNKNOWN'}, 'mileageInKm': None, 'doors': None, 'windows': None, 'lights': None}, 'local': None, 'errors': [{'type': 'DOORS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/access/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'WINDOWS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/access/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'PARKING_LIGHTS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/lights/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'MILEAGE_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/measurements": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}]}

2022-12-28 16:30:23.231 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:30:28.322 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': '2022-12-28T13:18:32.05Z', 'status': {'open': 'NO', 'locked': 'YES'}, 'mileageInKm': None, 'doors': [{'name': 'BONNET', 'status': 'CLOSED'}, {'name': 'TRUNK', 'status': 'LOCKED'}, {'name': 'REAR_RIGHT', 'status': 'LOCKED'}, {'name': 'REAR_LEFT', 'status': 'LOCKED'}, {'name': 'FRONT_RIGHT', 'status': 'LOCKED'}, {'name': 'FRONT_LEFT', 'status': 'LOCKED'}], 'windows': [{'name': 'SUN_ROOF', 'status': 'CLOSED'}, {'name': 'ROOF_COVER', 'status': 'UNSUPPORTED'}, {'name': 'SUN_ROOF_REAR', 'status': 'UNSUPPORTED'}, {'name': 'FRONT_LEFT', 'status': 'CLOSED'}, {'name': 'FRONT_RIGHT', 'status': 'CLOSED'}, {'name': 'REAR_LEFT', 'status': 'CLOSED'}, {'name': 'REAR_RIGHT', 'status': 'CLOSED'}], 'lights': None}, 'local': None, 'errors': [{'type': 'PARKING_LIGHTS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/lights/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'MILEAGE_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/measurements": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}]}

2022-12-28 16:31:28.234 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:31:30.319 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': '2022-12-28T13:18:32.05Z', 'status': {'open': 'NO', 'locked': 'YES'}, 'mileageInKm': 5150.0, 'doors': [{'name': 'BONNET', 'status': 'CLOSED'}, {'name': 'TRUNK', 'status': 'LOCKED'}, {'name': 'REAR_RIGHT', 'status': 'LOCKED'}, {'name': 'REAR_LEFT', 'status': 'LOCKED'}, {'name': 'FRONT_RIGHT', 'status': 'LOCKED'}, {'name': 'FRONT_LEFT', 'status': 'LOCKED'}], 'windows': [{'name': 'SUN_ROOF', 'status': 'CLOSED'}, {'name': 'ROOF_COVER', 'status': 'UNSUPPORTED'}, {'name': 'SUN_ROOF_REAR', 'status': 'UNSUPPORTED'}, {'name': 'FRONT_LEFT', 'status': 'CLOSED'}, {'name': 'FRONT_RIGHT', 'status': 'CLOSED'}, {'name': 'REAR_LEFT', 'status': 'CLOSED'}, {'name': 'REAR_RIGHT', 'status': 'CLOSED'}], 'lights': {'overallStatus': 'OFF', 'lightsStatus': [{'name': 'RIGHT', 'status': 'OFF'}, {'name': 'LEFT', 'status': 'OFF'}]}}, 'local': None, 'errors': []}

2022-12-28 16:32:30.231 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}"

2022-12-28 16:32:35.321 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/{VIN}" returned with status code [200], response: {'remote': {'capturedAt': '2022-12-28T13:18:13.739Z', 'status': {'open': 'UNKNOWN', 'locked': 'UNKNOWN'}, 'mileageInKm': None, 'doors': None, 'windows': None, 'lights': {'overallStatus': 'OFF', 'lightsStatus': [{'name': 'RIGHT', 'status': 'OFF'}, {'name': 'LEFT', 'status': 'OFF'}]}}, 'local': None, 'errors': [{'type': 'DOORS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/access/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'WINDOWS_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/access/status": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}, {'type': 'MILEAGE_LOAD_FAILED', 'description': 'I/O error on GET request for "https://cardata.apps.emea.vwapps.io/vehicles/{VIN}/measurements": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool'}]}

**Comment by RamonQu** [comment] 2022-12-28 21:14
I just checked. The iOS-app uses the exact same API-endpoint as the HA-Skodaconnect integration and therefore has the same problems in the MySkoda-App.

**Comment by lucius-the** [comment] 2022-12-28 23:52
> @lucius-the Can you look at the history of the applicable sensors within HA? Do they open/close several times during the day? If so, it has probably the same cause.

They do change during the day, from unlocked to locked.
Back at the time when I reported the problem, the Skoda app showed the correct values and values in HA were incorrect, even after forced refresh.

I just force refreshed it now - and now it shows ok both in the app and in HA. What changed in the mean time - I don't know. I didn't update anything, I'm still on 1.0.72 -> HACS doesn't even offer any update for me (strange thing, because I see new releases here on GitHub).

**Comment by RamonQu** [comment] 2022-12-30 11:41
It really due to the lack of stability of the Skoda servers. I also got errors in MySkoda-app. I included two screenshots in this comment. 

I would be great of the errors WINDOWS_LOAD_FAILED, MILEAGE_LOAD_FAILED, PARKING_LIGHTS_LOAD_FAILED, DOORS_LOAD_FAILED would be catched and the status of the sensor would not be updated due to the “available” status UKNOWN or None. 

For example errors in the MySkoda-app:

Small text at the top. The update did not succeed. Try again later. 
![B0D555C4-F8FE-4B19-B56C-6406ECDCDC9C](https://user-images.githubusercontent.com/113984457/210065900-045149b7-82d4-4fce-aaf5-abb7ab0ed6d0.png)


Lock-state and doors/windows not available. Lights status seemed to be available in this call. 
![9F9AC29D-604E-4175-AD04-D725B99FCFE3](https://user-images.githubusercontent.com/113984457/210065903-007eed6b-1a16-447b-bdbb-4d1aa1c587a4.png)

**Comment by Farfar** [comment] 2023-01-02 14:58
Thanks for the debugs. I've added some crude error handling that will attempt to re-use last values for doors, windows, lights and mileage if an error is encountered in received data.
Fix will be included in next library version (next after 1.3.0).

**Comment by RamonQu** [comment] 2023-01-02 16:11
Thanks, that's great @Farfar ! I saw [the new error handling](https://github.com/lendy007/skodaconnect/compare/1.3.0...main).

**Comment by Farfar** [comment] 2023-01-05 13:12
Please report back if version 1.2 still have this issue

**Comment by RamonQu** [comment] 2023-01-06 21:59
The first signs are good. This issue looks solved. I can confirm after a couple of days, I had some token issues lately ;).

**Comment by RamonQu** [comment] 2023-01-09 22:13
Confirmed. This fixes the issue. Thanks @Farfar Good job!

**Comment by markblokpoel** [comment] 2023-02-07 18:44
Hi, I’m not sure if this issue is related, but it seems similar so I’m replying here. My Enyaq charge limit is constantly alternating between 0 and 80 (the set charge limit). Could this be related to the issues described here? I’m on HA Core 2023.1.7 HACS 1.30.1 and Skoda Connect integration 1.2.3.

**Comment by Farfar** [comment] 2023-03-22 09:33
Yes it's related. The Skoda API used for Enyaq isn't really consistent. If the frontend to backend connection fails or gives errors the API will return incorrect values. So the issue is how the API sends data when the VAG servers have problems.
At the moment there's attempted fixes for this for some sensors but not working 100%.
Further development of fixes won't be until version 2.0 of underlying library.

**Comment by dvx76** [comment] 2023-07-22 15:49
@markblokpoel @lucius-the , just curious if you're still seeing these issues on the current version (1.2.5)?

**Comment by dvx76** [comment] 2023-08-31 15:57
Closing as this appears solved based on the last comment and no further updates.

**Closed by dvx76** 2023-08-31 15:57 UTC
Labels: bug
