### ISSUE TITLE
Could not login to Skoda Connect

### ISSUE THREAD

**Issue by AfcaEric** [skodaconnect/homeassistant-skodaconnect#232] opened 2023-11-06 07:50 UTC
**Describe the bug**
Since 4-5 days my Skoda Connect wasn't working anymore. Removing the configured device and trying to re-add results in a "Could not login to Skoda Connect". Import note: my credentials are working fine on the official app, but i did see there was a new MySkoda app. Maybe it's related?

**Is this working in MySkoda app?***
Yes, my credentials are working fine in MySkoda App.

**Latest working release**
Not sure about the version, but it was working about a week ago.

**Additional context**
As said earlier: Skoda did seem to release a new MySkoda app (not an update, it's a new/seperate install). Maybe it's related?

**Comment by dvx76** [comment] 2023-11-06 07:52
Duplicate of #227 .

Please update the integration to the latest version 1.2.7.

**Closed by dvx76** 2023-11-06 07:52 UTC
Labels: bug

**Comment by AfcaEric** [comment] 2023-11-06 10:56
> Duplicate of #227 .
> 
> Please update the integration to the latest version 1.2.7.

Thanks, updated and works fine!
