### ISSUE TITLE
Login failure, but it works on the website

### ISSUE THREAD

**Issue by Cereal2nd** [skodaconnect/homeassistant-skodaconnect#238] opened 2023-12-11 15:01 UTC
**Describe the bug**
Login failure

**Is this working in MySkoda app?***
Yes

**Latest working release**
It never worked

**Debug logs**
```
2023-12-11 15:57:20.091 DEBUG (MainThread) [custom_components.skodaconnect.config_flow] Creating connection to Skoda Connect
2023-12-11 15:57:20.093 INFO (MainThread) [skodaconnect.connection] Unofficial Skoda Connect library, version 1.3.8
2023-12-11 15:57:20.094 DEBUG (MainThread) [skodaconnect.connection] Using service https://msg.volkswagen.de
2023-12-11 15:57:20.097 INFO (MainThread) [skodaconnect.connection] Initiating new login
2023-12-11 15:57:20.099 DEBUG (MainThread) [skodaconnect.connection] Starting authorization process for client technical
2023-12-11 15:57:20.362 DEBUG (MainThread) [skodaconnect.connection] User is not logged on, use signin service
2023-12-11 15:57:20.425 DEBUG (MainThread) [skodaconnect.connection] Found HTML credentials form, extracting attributes
2023-12-11 15:57:20.426 DEBUG (MainThread) [skodaconnect.connection] Start login process for user maikel.punie@gmail.com
2023-12-11 15:57:20.590 DEBUG (MainThread) [skodaconnect.connection] Found dynamic credentials form, extracting attributes
2023-12-11 15:57:20.591 DEBUG (MainThread) [skodaconnect.connection] Script JSON data: {'clientLegalEntityModel': {'clientId': 'f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com', 'clientAppName': 'ŠKODA App & Portal', 'clientAppDisplayName': 'ŠKODA App & Portal', 'legalEntityInfo': {'name': 'ŠKODA', 'shortName': 'SKODA', 'productName': 'ŠKODA ID', 'theme': 'skoda_2023', 'defaultLanguage': 'cs', 'termAndConditionsType': 'DEFAULT', 'legalProperties': {'revokeDataContact': 'infoline@skoda-auto.cz', 'imprintText': 'IMPRINT', 'countryOfJurisdiction': 'CZ'}}, 'informalLanguage': False, 'legalEntityCode': 'skoda', 'imprintTextKey': 'imprint.link.text'}, 'template': 'loginAuthenticate', 'hmac': 'a7da2d4a31dda372f8b8eb88a976000c8ea25a4e9211f90c088d8fedaede8dc3', 'useClientRendering': True, 'titleKey': 'title.login.password', 'title': None, 'emailPasswordForm': {'@class': 'com.volkswagen.identitykit.signin.domain.model.dto.EmailPasswordForm', 'email': 'XXXXXXXXX', 'password': None}, 'error': None, 'relayState': 'XXXXXXXXX', 'nextButtonDisabled': False, 'enableNextButtonAfterSeconds': 0, 'postAction': 'login/authenticate', 'identifierUrl': 'login/identifier'}
2023-12-11 15:57:20.592 DEBUG (MainThread) [skodaconnect.connection] Finalizing login
2023-12-11 15:57:21.158 DEBUG (MainThread) [skodaconnect.connection] Received authorization code, exchange for tokens.
2023-12-11 15:57:21.246 DEBUG (MainThread) [skodaconnect.connection] Got <ClientResponse(https://api.connect.skoda-auto.cz/api/v1/authentication/token?systemId=TECHNICAL) [410 Gone]>
<CIMultiDictProxy('Content-Length': '18', 'Content-Type': 'text/plain', 'Date': 'Mon, 11 Dec 2023 14:57:20 GMT', 'Server': 'istio-envoy', 'Connection': 'close')>

2023-12-11 15:57:21.247 ERROR (MainThread) [skodaconnect.connection] Token exchange failed. Request status: 410
2023-12-11 15:57:21.247 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Login failed with error: Token exchange failed. Request status: 410
```

**Installation:**
 - Home Assistant variant: Supervised
 - Python version 3.11
 - Python library versions
```
Package            Version   Editable project location
------------------ --------- -------------------------
backoff            2.2.1
blinker            1.5
certifi            2022.9.24
chardet            5.1.0
charset-normalizer 3.0.1
cryptography       38.0.4
cupshelpers        1.0
dbus-python        1.3.2
distro             1.8.0
gyp                0.1
httplib2           0.20.4
idna               3.3
lazr.restfulclient 0.14.5
lazr.uri           1.0.6
ntpsec             1.2.2
oauthlib           3.2.2
pip                23.0.1
pycairo            1.20.1
pycups             2.0.1
pycurl             7.45.2
PyGObject          3.42.2
PyJWT              2.6.0
pyparsing          3.0.9
pyserial           3.5
pyserial-asyncio   0.6
PySimpleSOAP       1.16.2
pysmbc             1.0.23
python-apt         2.6.0
python-debian      0.1.49
python-debianbts   4.0.1
reportbug          12.0.0
requests           2.28.1
setuptools         66.1.1
six                1.16.0
urllib3            1.26.12
velbus-aio         2023.10.1 /home/cereal/velbus-aio
wadllib            1.3.6
wheel              0.38.4

```

**Comment by MaZa78** [comment] 2023-12-11 15:27
Duplicate of #237

**Closed** 2023-12-11 15:34 UTC
Labels: bug
