### ISSUE TITLE
Cannot login to integration - Invalid token "None"

### ISSUE THREAD

**Issue by ChrisZ32** [skodaconnect/homeassistant-skodaconnect#280] opened 2024-05-01 22:11 UTC
**Please search issues in https://github.com/skodaconnect/skodaconnect and https://github.com/skodaconnect/homeassistant-skodaconnect for duplicates or fixes before reporting a new issue.**

**Describe the bug**
Trying this integration for the first time (only got my Enyaq today) and I can't login. After supplying my credentials I get a popup with just 'Error' as a title but no other content. In the logs, I see this:

********************
This error originated from a custom integration.

Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:117
integration: Skoda Connect (documentation, issues)
First occurred: 22:50:31 (2 occurrences)
Last logged: 23:08:36

Fetch vehicles failed with error: Invalid token "None"
********************

**Is this working in MySkoda app?**
I can connect fine through 'MySkoda' Android app but I cannot connect through 'MySkoda Essentials'. I cannot add my car in the essentials version of the android app, it gets stuck - the car thinks I have logged in, but the app doesn't. I cannot access Skoda Connect via the web portal, if I try to register my car it tells me to use the app. Logging in to the essentials app seems to be common workaround, but seems to me they are phasing out that app?

**Latest working release**
NA (new user)

**Installation:**
 - Hass OS (Core 2024.5.0, Supervisor 2024.04.4, Operating System 12.2, Frontend 20240501.0)
 - skodaconnect v1.2.10

**Additional context**
Please let me know if there is anymore info I can provide!

**Comment by dvx76** [comment] 2024-05-02 08:03
Yep this seems to be a new change on the API side affecting new accounts/vehicles. Other cases https://github.com/skodaconnect/skodaconnect/issues/126 and https://github.com/skodaconnect/homeassistant-skodaconnect/issues/279

No solution for this at the moment but being discussed in #homeassitant on Discord.

**Comment by mellowtronik** [comment] 2024-05-04 23:51
@dvx76 

hello, I confirm that it is exactly the same problem as @MarcelMertens and @ChrisZ32

**Comment by dvx76** [comment] 2024-05-05 10:22
To centralize progress and updates I'm going to close this as a duplicate of https://github.com/skodaconnect/skodaconnect/issues/126 since it has the best level of detail so far.

**Comment by dvx76** [comment] 2024-05-29 19:51
Hi,

Most users have now received the same email wrt the Essentials app EOL. We also know that for new vehicles/accounts the Essentials app, and consequently this integration, is already not working.

There are only a few active developers working on this integration but we are aware of this and we are (slowly) working on making the integration compatible with the new MySkoda app/API. There are no timelines and in fact no guarantee we will get this working. Please be patient and do not open new issues reporting the same thing.

**Closed by dvx76** 2024-05-29 19:51 UTC
Labels: bug
