### ISSUE TITLE
Integration stopped working with HA Update

### ISSUE THREAD

**Issue by giganode** [skodaconnect/homeassistant-skodaconnect#266] opened 2024-02-21 09:43 UTC
Hey!

With updating to the following version of home assistant, the integration stopped working.
Host is a Raspberri Pi4b.

<img width="462" alt="image" src="https://github.com/skodaconnect/homeassistant-skodaconnect/assets/74789086/1bc67288-5d4e-4c88-8a1a-76ea51b0e80c">

`Logger: homeassistant.setup
Source: setup.py:251
First occurred: 10:38:54 (1 occurrences)
Last logged: 10:38:54

Setup failed for custom integration 'skodaconnect': Unable to import component: No module named 'skodaconnect'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/skodaconnect/__init__.py", line 32, in <module>
    from skodaconnect import Connection
ModuleNotFoundError: No module named 'skodaconnect'
`

Any recommendations?

**Comment by dvx76** [comment] 2024-02-21 11:01
Hi,

I have core 2024.2.2 (but not with haOS) working ok.

Are you installing the integration through HACS?

**Comment by giganode** [comment] 2024-02-21 13:46
> Are you installing the integration through HACS?

Yes! I also removed it und reinstalled it.

**Comment by dvx76** [comment] 2024-02-24 13:12
I can't reproduce this on a clean install of HA Core 2024.02 with the latest HACS and integration. Logs below. Can you please provide full logs of the HACS install + adding/configuring the integration?

```
# Add in HACS:
2024-02-24 14:07:54.796 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Running pre installation steps
2024-02-24 14:07:54.796 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Pre installation steps completed
2024-02-24 14:07:54.797 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Running installation steps
2024-02-24 14:07:56.379 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of __init__.py completed
2024-02-24 14:07:56.380 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of binary_sensor.py completed
2024-02-24 14:07:56.412 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of services.yaml completed
2024-02-24 14:07:56.413 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of lock.py completed
2024-02-24 14:07:56.418 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of config_flow.py completed
2024-02-24 14:07:56.420 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of manifest.json completed
2024-02-24 14:07:56.421 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of sensor.py completed
2024-02-24 14:07:56.427 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of const.py completed
2024-02-24 14:07:56.430 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of climate.py completed
2024-02-24 14:07:56.435 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of device_tracker.py completed
2024-02-24 14:07:57.559 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of switch.py completed
2024-02-24 14:07:57.567 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of strings.json completed
2024-02-24 14:07:57.586 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of de.json completed
2024-02-24 14:07:57.592 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of en.json completed
2024-02-24 14:07:57.599 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of nb.json completed
2024-02-24 14:07:57.607 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of pl.json completed
2024-02-24 14:07:57.617 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of ru.json completed
2024-02-24 14:07:57.651 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of it.json completed
2024-02-24 14:07:57.657 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of nl.json completed
2024-02-24 14:07:57.665 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of nn.json completed
2024-02-24 14:07:58.742 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of sv.json completed
2024-02-24 14:07:58.759 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Download of sk.json completed
2024-02-24 14:07:59.760 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Installation steps completed
2024-02-24 14:07:59.760 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Running post installation steps
2024-02-24 14:07:59.760 INFO (MainThread) [custom_components.hacs] Reloading custom_component cache
2024-02-24 14:07:59.761 INFO (SyncWorker_3) [homeassistant.loader] Loaded skodaconnect from custom_components.skodaconnect
2024-02-24 14:07:59.761 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration skodaconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-24 14:07:59.762 INFO (SyncWorker_3) [homeassistant.loader] Loaded hacs from custom_components.hacs
2024-02-24 14:07:59.762 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-24 14:07:59.762 INFO (MainThread) [custom_components.hacs] Custom_component cache reloaded
2024-02-24 14:07:59.763 INFO (MainThread) [custom_components.hacs] <Integration skodaconnect/homeassistant-skodaconnect> Post installation steps completed
```

```
# Add and Configure integration:
2024-02-24 14:08:48.092 INFO (SyncWorker_0) [homeassistant.loader] Loaded waze_travel_time from homeassistant.components.waze_travel_time
2024-02-24 14:08:48.092 INFO (SyncWorker_0) [homeassistant.loader] Loaded homekit_controller from homeassistant.components.homekit_controller
2024-02-24 14:08:48.093 INFO (SyncWorker_0) [homeassistant.loader] Loaded utility_meter from homeassistant.components.utility_meter
2024-02-24 14:08:48.094 INFO (SyncWorker_0) [homeassistant.loader] Loaded switch_as_x from homeassistant.components.switch_as_x
2024-02-24 14:08:48.094 INFO (SyncWorker_0) [homeassistant.loader] Loaded workday from homeassistant.components.workday
2024-02-24 14:08:48.094 INFO (SyncWorker_0) [homeassistant.loader] Loaded derivative from homeassistant.components.derivative
2024-02-24 14:08:48.095 INFO (SyncWorker_0) [homeassistant.loader] Loaded generic from homeassistant.components.generic
2024-02-24 14:08:48.095 INFO (SyncWorker_0) [homeassistant.loader] Loaded aurora from homeassistant.components.aurora
2024-02-24 14:08:48.096 INFO (SyncWorker_0) [homeassistant.loader] Loaded holiday from homeassistant.components.holiday
2024-02-24 14:08:48.097 INFO (SyncWorker_0) [homeassistant.loader] Loaded threshold from homeassistant.components.threshold
2024-02-24 14:08:48.098 INFO (SyncWorker_0) [homeassistant.loader] Loaded min_max from homeassistant.components.min_max
2024-02-24 14:08:48.099 INFO (SyncWorker_0) [homeassistant.loader] Loaded local_ip from homeassistant.components.local_ip
2024-02-24 14:08:48.099 INFO (SyncWorker_0) [homeassistant.loader] Loaded local_todo from homeassistant.components.local_todo
2024-02-24 14:08:48.101 INFO (SyncWorker_0) [homeassistant.loader] Loaded google_travel_time from homeassistant.components.google_travel_time
2024-02-24 14:08:48.103 INFO (SyncWorker_0) [homeassistant.loader] Loaded growatt_server from homeassistant.components.growatt_server
2024-02-24 14:08:48.104 INFO (SyncWorker_0) [homeassistant.loader] Loaded shopping_list from homeassistant.components.shopping_list
2024-02-24 14:08:48.105 INFO (SyncWorker_0) [homeassistant.loader] Loaded time_date from homeassistant.components.time_date
2024-02-24 14:08:48.106 INFO (SyncWorker_0) [homeassistant.loader] Loaded rpi_power from homeassistant.components.rpi_power
2024-02-24 14:08:48.106 INFO (SyncWorker_0) [homeassistant.loader] Loaded emulated_roku from homeassistant.components.emulated_roku
2024-02-24 14:08:48.107 INFO (SyncWorker_0) [homeassistant.loader] Loaded tod from homeassistant.components.tod
2024-02-24 14:08:48.108 INFO (SyncWorker_0) [homeassistant.loader] Loaded local_calendar from homeassistant.components.local_calendar
2024-02-24 14:08:48.108 INFO (SyncWorker_0) [homeassistant.loader] Loaded cert_expiry from homeassistant.components.cert_expiry
2024-02-24 14:08:48.109 INFO (SyncWorker_0) [homeassistant.loader] Loaded uptime from homeassistant.components.uptime
2024-02-24 14:08:48.110 INFO (SyncWorker_0) [homeassistant.loader] Loaded moon from homeassistant.components.moon
2024-02-24 14:08:48.110 INFO (SyncWorker_0) [homeassistant.loader] Loaded proximity from homeassistant.components.proximity
2024-02-24 14:08:48.111 INFO (SyncWorker_0) [homeassistant.loader] Loaded garages_amsterdam from homeassistant.components.garages_amsterdam
2024-02-24 14:08:48.112 INFO (SyncWorker_0) [homeassistant.loader] Loaded nextbus from homeassistant.components.nextbus
2024-02-24 14:08:48.112 INFO (SyncWorker_0) [homeassistant.loader] Loaded integration from homeassistant.components.integration
2024-02-24 14:08:48.113 INFO (SyncWorker_0) [homeassistant.loader] Loaded cpuspeed from homeassistant.components.cpuspeed
2024-02-24 14:08:48.113 INFO (SyncWorker_0) [homeassistant.loader] Loaded season from homeassistant.components.season
2024-02-24 14:08:48.114 INFO (SyncWorker_0) [homeassistant.loader] Loaded zodiac from homeassistant.components.zodiac
2024-02-24 14:08:48.116 INFO (SyncWorker_0) [homeassistant.loader] Loaded filesize from homeassistant.components.filesize
2024-02-24 14:08:48.116 INFO (SyncWorker_0) [homeassistant.loader] Loaded islamic_prayer_times from homeassistant.components.islamic_prayer_times
2024-02-24 14:08:48.117 INFO (SyncWorker_0) [homeassistant.loader] Loaded demo from homeassistant.components.demo
2024-02-24 14:08:48.118 INFO (SyncWorker_0) [homeassistant.loader] Loaded plant from homeassistant.components.plant
2024-02-24 14:08:48.119 INFO (SyncWorker_0) [homeassistant.loader] Loaded moehlenhoff_alpha2 from homeassistant.components.moehlenhoff_alpha2
2024-02-24 14:08:48.120 INFO (SyncWorker_0) [homeassistant.loader] Loaded version from homeassistant.components.version
2024-02-24 14:08:48.121 INFO (SyncWorker_0) [homeassistant.loader] Loaded nmap_tracker from homeassistant.components.nmap_tracker
2024-02-24 14:08:48.122 INFO (SyncWorker_0) [homeassistant.loader] Loaded alert from homeassistant.components.alert
2024-02-24 14:08:51.170 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of skodaconnect==1.3.10
2024-02-24 14:09:33.739 INFO (MainThread) [skodaconnect.connection] Unofficial Skoda Connect library, version 1.3.10
2024-02-24 14:09:33.739 WARNING (MainThread) [homeassistant.data_entry_flow] custom_components.skodaconnect.config_flow::SkodaConnectConfigFlow calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
2024-02-24 14:09:33.740 INFO (MainThread) [skodaconnect.connection] Initiating new login
2024-02-24 14:09:35.162 INFO (MainThread) [skodaconnect.connection] Token for technical verified OK.
2024-02-24 14:09:35.763 INFO (MainThread) [skodaconnect.connection] Token for connect verified OK.
2024-02-24 14:09:36.850 INFO (MainThread) [custom_components.skodaconnect.config_flow] Found data for VIN: REDACTED from Skoda Connect
2024-02-24 14:09:36.852 INFO (MainThread) [custom_components.skodaconnect.config_flow] Found data for VIN: REDACTED from Skoda Connect
2024-02-24 14:10:16.120 INFO (MainThread) [homeassistant.setup] Setting up skodaconnect
2024-02-24 14:10:16.120 INFO (MainThread) [homeassistant.setup] Setup of domain skodaconnect took 0.0 seconds
2024-02-24 14:10:16.121 INFO (MainThread) [skodaconnect.connection] Unofficial Skoda Connect library, version 1.3.10
2024-02-24 14:10:16.121 INFO (MainThread) [skodaconnect.connection] Initiating new login
2024-02-24 14:10:17.510 INFO (MainThread) [skodaconnect.connection] Token for technical verified OK.
2024-02-24 14:10:18.193 INFO (MainThread) [skodaconnect.connection] Token for connect verified OK.
```

**Comment by giganode** [comment] 2024-03-01 19:29
It was absolutely impossible.. I think there was something broken during update.

I wasn't able to remove the integration anymore. everything was basically bricked.

Created a full backup and loaded it onto a x86 machine and everything was working immediately.

Thank you anyway. Sadly I can't provide any more information.

**Comment by dvx76** [comment] 2024-04-13 21:16
Closing. No logs and can't reproduce.

**Closed by dvx76** 2024-04-13 21:16 UTC
