### ISSUE TITLE
Homeassistant depreceated function for GPS

### ISSUE THREAD

**Issue by Kilowatt-W** [skodaconnect/homeassistant-skodaconnect#255] opened 2024-01-17 07:29 UTC
Hi there

got this message from logs :

SOURCE_TYPE_GPS was used from skodaconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, 

Greetings Kilowatt :-)

**Comment by dvx76** [comment] 2024-01-17 08:27
Duplicate of #249 and #253, fixed in #250

**Closed by dvx76** 2024-01-17 08:27 UTC
