### ISSUE TITLE
Login failed with error: Token exchange failed. Request status: 429

### ISSUE THREAD

**Issue by mvzut** [skodaconnect/homeassistant-skodaconnect#228] opened 2023-11-05 07:46 UTC
Yesterday (4 November) there were severe server issues almost the whole day. The official Škoda apps didn't work but also third party apps, such as the HA integration and Tronity, could not fetch any data.
In the evening it seemed to be solved: the Škoda apps worked and also Tronity was able to fetch data again. However, I still could get the HA integration to connect. I even uninstalled it and tried to install it again, but now I can't even get past the first login screen.

In the logs I see this error:

Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:103
Integration: Skoda Connect (documentation, issues)
First occurred: 4 november 2023 om 23:30:50 (3 occurrences)
Last logged: 08:29:38

Login failed with error: Token exchange failed. Request status: 429

I am using the latest version of HAOS on a RPi. The integration has always worked flawlessly until yesterday. The app still works and also the online version of Skoda Connect.

**Comment by Farfar** [comment] 2023-11-05 07:47
Duplicate of #227

**Closed by Farfar** 2023-11-05 07:47 UTC
Labels: bug
