### ISSUE TITLE
Refreshing tokens for "connect" failing since 12/11/2023 ~noon CET

### ISSUE THREAD

**Issue by muernst35** [skodaconnect/homeassistant-skodaconnect#241] opened 2023-12-11 18:50 UTC
'Noticed today that token refresh is failing for the following reason:
...
2023-12-11 19:23:09.772 DEBUG (MainThread) [skodaconnect.connection] Successfully verified refresh token audience and signature
2023-12-11 19:23:09.773 INFO (MainThread) [skodaconnect.connection] Restored token for client "connect", valid until 2024-06-08 13:04:05
2023-12-11 19:23:09.773 DEBUG (MainThread) [skodaconnect.connection] No valid access token for "connect"
2023-12-11 19:23:09.773 DEBUG (MainThread) [skodaconnect.connection] Refreshing tokens for client "connect"
2023-12-11 19:23:09.862 WARNING (MainThread) [skodaconnect.connection] Something went wrong when refreshing tokens for "connect".
2023-12-11 19:23:09.865 DEBUG (MainThread) [skodaconnect.connection] Response: <ClientResponse(https://api.connect.skoda-auto.cz/api/v1/authentication/token/refresh?systemId=CONNECT) [410 Gone]>

Looks like Skoda has been working on the MySkoda Essentials App, which was unavailable for a some time this afternoon (12/11/2023).
Error code [410 Gone] meaning page is no longer available (?)
The integration I'm using is based on "Unofficial Skoda Connect library, version 1.3.8"

I'd appreciate if an expert could take a look - many thanks in advance.

**Comment by Farfar** [comment] 2023-12-11 19:04
Issue is duplicate of #237 and #238.
Please update to latest version which contains fix.

**Closed by Farfar** 2023-12-11 19:04 UTC
