### ISSUE TITLE
Electric consumption sensor missing

### ISSUE THREAD

**Issue by fwestenberg** [skodaconnect/homeassistant-skodaconnect#147] opened 2022-11-13 20:35 UTC
The Skoda app shows two values:
- Electric consumption: the total consumption of the EV
- Engine consumption: the energy used by the motor

In HA only the second values is shown, which is always lower than the first one. Best would probably to add the second (engine) sensor, and use the first for the original electric consumption corresponding to the app. 

**Installation**
 - Home Assistant variant: Hass OS
 - HACS installed
 - Skoda Connect addon 1.0.72

**Comment by fwestenberg** [comment] 2022-11-13 20:41
![IMG_20221113_214013](https://user-images.githubusercontent.com/47930023/201543610-7dccc654-0c32-465f-ba23-7030dfde63ac.jpg)
![IMG_20221113_213955](https://user-images.githubusercontent.com/47930023/201543611-473da00e-8fb6-48da-b4d4-3cc3e5305d20.jpg)
![IMG_20221113_213935](https://user-images.githubusercontent.com/47930023/201543614-7b28ca85-f082-4d0b-8f50-9d9d85f9bd4f.jpg)
![IMG_20221113_213919](https://user-images.githubusercontent.com/47930023/201543615-f7067c20-798b-4c46-92a2-41c8c83ace80.jpg)

**Comment by Farfar** [comment] 2022-11-18 09:37
This data hasn't been available previously, must have been added last 6 months.
Please provide full debug (HTTP response) data and I'll take a look and implement this in futurue release.

**Comment by RamonQu** [comment] 2022-12-12 12:44
I have seen this feature in they MySkoda-app of  my previous car (Skoda Octavia PHEV), but it's not implemented in Enyaq (yet). At least not in ME3.0. @fwestenberg Which car are you driving?

**Comment by fwestenberg** [comment] 2022-12-12 12:45
I'm driving a Citigo iV.

**Comment by fwestenberg** [comment] 2022-12-12 13:46
> This data hasn't been available previously, must have been added last 6 months. Please provide full debug (HTTP response) data and I'll take a look and implement this in futurue release.

How can I obtain this data? I tried a debug, but only see data like this in the log:

'2022-12-12 14:42:56.831 DEBUG (MainThread) [skodaconnect.connection] Request for "https://msg.volkswagen.de/fs-car/bs/tripstatistics/v1/skoda/CZ/vehicles/TMBZAAAABBC123456/tripdata/shortTerm?newest" returned with status code [200]'

**Comment by RamonQu** [comment] 2022-12-12 14:02
If you are using a iPhone, this is how I did it:
- Set-up a proxy (e.g. https://www.charlesproxy.com/ ) on a desktop. 
- Let your phone/app connect to that proxy so Charles Proxy on your desktop let's you view your iphone traffic. 
- Install Root certifcate on your phone to view secure traffic
- Trust certifcate on iPhone (this is an additional step in info)
- Enable SSL Proxy for the domain skoda-auto.cz from your list of traffic 

A video of the instructions is here: https://www.youtube.com/watch?v=r7aV39-CKg4

Than capture the traffic and how that interacts with the app

I hope this helps.

**Comment by Farfar** [comment] 2022-12-23 12:16
> * Enable SSL Proxy for the domain skoda-auto.cz from your list of traffic

This won't work as the app (at least on android) use SSL pinning to prevent MITM spying.

**Comment by klavdijc** [comment] 2023-01-01 19:47
Is it possible to get the status of the 12v battery?
It has gone blank several times and I haven't started the car.

**Comment by Farfar** [comment] 2023-01-01 19:50
> Is it possible to get the status of the 12v battery? It has gone blank several times and I haven't started the car.

Not that I know of. I haven't seen any information related to 12v battery in all of the API responses I've processed.

**Comment by klavdijc** [comment] 2023-01-01 20:03
Too bad.
I am looking for a way to get this data in HA.
I mostly use FOBARO modules, which have input voltages of 0-10V.
You have an idea.
But it has to be simple because I'm a beginner.

**Comment by Farfar** [comment] 2023-01-01 21:00
> Too bad. I am looking for a way to get this data in HA. I mostly use FOBARO modules, which have input voltages of 0-10V. You have an idea. But it has to be simple because I'm a beginner.

There's probably some OBD dongle that sends data about 12v battery. The problem is how to get the data from the car to Home Assistant if you don't have wifi coverage.

**Comment by RamonQu** [comment] 2023-01-01 21:16
@klavdijc That's really a different feature-request than what @fwestenberg raised on Nov 13th 2022 in this issue. Because battery voltage info is not available in the API there is no real simple solution. Someone had arranged it with some components over here: https://community.home-assistant.io/t/monitor-your-car-battery-in-home-assistant/201508  . I don't know the Fobaro modules, but they are probably for a real different use. OBD2-plug won't help you out either, they will stop their communication when the car is off.

@fwestenberg Any chance to gather the data yet using a proxy? It still works for me on a iPhone as [mentioned three weeks ago](https://github.com/lendy007/homeassistant-skodaconnect/issues/147#issuecomment-1346563650 ), but is [not possible on Android phones as Farfar describes](https://github.com/lendy007/homeassistant-skodaconnect/issues/147#issuecomment-1363906311) in a comment. If you can't gather the data or don't know anybody who can I think it's better to close this feature-request. I can do it for you, but I'm not sure whether you willing to share you login-credentials. I'm also from the Netherlands.

**Comment by klavdijc** [comment] 2023-01-02 08:40
Guys.
Thank you for your efforts. The described solution is really complicated for me. I'll have to make sure I start the car at least every third day so it doesn't drain my battery.
I live in Slovenia and I started with FIBARO and NETATMO modules, but now I'm switching to HA, which is excellent with integrations to different systems.
Please close this feature-request.

**Comment by Farfar** [comment] 2023-01-02 13:37
I forgot for a minute that the feature request was a different one, reopening.

**Comment by WebSpider** [comment] 2023-09-22 09:23
Please use the suggested template sensor for now

**Closed by WebSpider** 2023-09-22 09:23 UTC
Labels: enhancement
