### ISSUE TITLE
Impossible de se connecter sur Home assistant

### ISSUE THREAD

**Issue by mellowtronik** [skodaconnect/homeassistant-skodaconnect#279] opened 2024-05-01 15:08 UTC
**Please search issues in https://github.com/skodaconnect/skodaconnect and https://github.com/skodaconnect/homeassistant-skodaconnect for duplicates or fixes before reporting a new issue.**

-----------------------------------------------------------------------------------

Good morning,
I have had a new Skoda ENYAQ since yesterday, the Skoda Essentials application does not work however it works perfectly with MYSKODA. I downloaded the integration with HACS, restarted and when I want to connect to Skoda Connect, I enter my email address and my password which is identical to the application and after a few seconds, I get a message "ERROR" therefore impossible to connect.
Can you help me, is there an update planned?
Thanks in advance.

Bonjour,
Je possède un skoda ENYAQ neuf depuis hier, l'application Skoda Essentials ne fonctionne par contre ça fonctionne parfaitement avec MYSKODA. J'ai téléchargé l'intégration avec HACS, redémarré et lorsque je veux me connecté à Skoda Connect, je rentre mon adresse mail et mon mot de passe qui est identique à l'application et au bout de quelques secondes, j'ai un message "ERREUR" donc impossible de se connecter. 
Pouvez-vous m'aider, est-ce qu'il y a une mise à jour prévue?
Merci par avance.

<img width="323" alt="image" src="https://github.com/skodaconnect/homeassistant-skodaconnect/assets/91826922/f18ef73f-50d6-4507-ae48-7c781e2117c9">

**Comment by dvx76** [comment] 2024-05-01 15:29
Looks like the same issue as https://github.com/skodaconnect/skodaconnect/issues/126 - same situation: new car (Enyaq), new account, MySkoda Essentials doesn't work.

Please provide a screenshot of the error in MySkoda Essentials as well as debug logs from Homeassisstant covering the moment where the error shows up in the UI.

**Comment by mellowtronik** [comment] 2024-05-04 23:47
@dvx76 
hello, 
yes it is exactly the same problem as @MarcelMertens😕

**Comment by dvx76** [comment] 2024-05-05 10:21
To centralize progress and updates I'm going to close this as a duplicate of https://github.com/skodaconnect/skodaconnect/issues/126 since it has the best level of detail so far.

**Closed by dvx76** 2024-05-05 10:21 UTC
